"""update 

Revision ID: 01a348ae407b
Revises: e9f87df5f1e5
Create Date: 2025-03-14 14:39:53.200143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01a348ae407b'
down_revision: Union[str, None] = 'e9f87df5f1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_call_id'), 'status_call', ['id'], unique=False)
    op.add_column('session_calls', sa.Column('call_status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session_calls', 'status_call', ['call_status_id'], ['id'], ondelete='CASCADE')
    op.drop_column('session_calls', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_calls', sa.Column('status', postgresql.ENUM('INITIATED', 'ONGOING', 'COMPLETED', 'MISSED', 'REJECTED', name='callstatus'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'session_calls', type_='foreignkey')
    op.drop_column('session_calls', 'call_status_id')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_status_call_id'), table_name='status_call')
    op.drop_table('status_call')
    # ### end Alembic commands ###
