"""update policeman

Revision ID: 022c4624c57e
Revises: 7eafb6acbe80
Create Date: 2025-03-11 09:46:32.609938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022c4624c57e'
down_revision: Union[str, None] = '7eafb6acbe80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policemans', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.create_unique_constraint(None, 'policemans', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'policemans', type_='unique')
    op.drop_column('policemans', 'verification_code')
    # ### end Alembic commands ###
