"""update models

Revision ID: 2f3398fb40bb
Revises: aeb09f9163df
Create Date: 2025-03-08 10:18:28.182403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3398fb40bb'
down_revision: Union[str, None] = 'aeb09f9163df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('statements_type_id_fkey', 'statements', type_='foreignkey')
    op.create_foreign_key(None, 'statements', 'types', ['type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.create_foreign_key('statements_type_id_fkey', 'statements', 'users', ['type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
