"""update_model_sessioncall

Revision ID: e9f87df5f1e5
Revises: 3a5915c0b019
Create Date: 2025-03-14 14:13:39.346584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.api.users.schemas.create import CallStatus

# revision identifiers, used by Alembic.
revision: str = 'e9f87df5f1e5'
down_revision: Union[str, None] = '3a5915c0b019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    callstatus_enum = sa.Enum(CallStatus, name='callstatus')
    callstatus_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('session_calls', sa.Column('status', sa.Enum('INITIATED', 'ONGOING', 'COMPLETED', 'MISSED', 'REJECTED', name='callstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_calls', 'status')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
