"""create_table_crimes

Revision ID: f189d884cd84
Revises: 022c4624c57e
Create Date: 2025-03-11 16:32:29.557129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f189d884cd84'
down_revision: Union[str, None] = '022c4624c57e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('geoposition', sa.String(length=255), nullable=True),
    sa.Column('period', sa.String(length=255), nullable=True),
    sa.Column('stat', sa.String(length=255), nullable=True),
    sa.Column('time_period', sa.String(length=255), nullable=True),
    sa.Column('organ', sa.String(length=255), nullable=True),
    sa.Column('year', sa.String(length=255), nullable=True),
    sa.Column('crime_code', sa.String(length=255), nullable=True),
    sa.Column('hard_code', sa.String(length=255), nullable=True),
    sa.Column('city_code', sa.String(length=255), nullable=True),
    sa.Column('ud', sa.String(length=255), nullable=True),
    sa.Column('objectid', sa.String(length=255), nullable=True),
    sa.Column('home_number', sa.String(length=255), nullable=True),
    sa.Column('reg_code', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crimes_id'), 'crimes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crimes_id'), table_name='crimes')
    op.drop_table('crimes')
    # ### end Alembic commands ###
